films/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^news/$', views.show_all_news, name='views.show_all_news'),
    url(r'^actors/$', views.actors_list, name='views.actors_list'),
    url(r'^$', views.film_list, name='film_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.film_list, name='film_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.film_detail, name='film_detail'),
    url(r'^actors/(?P<slug>[-\w]+)/$', views.actor_info, name='actor_info'),
    url(r'^news/(?P<slug>[-\w]+)/$', views.news_info, name='news_info'),
]

filmsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^', include('films.urls', namespace='films')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

films/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True, unique=True)

    class Meta:
        ordering =('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('films:film_list_by_category', args=[self.slug])



class Film(models.Model):
    category = models.ForeignKey(Category, related_name='films')
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    image = models.ImageField(upload_to='posters', blank=True)
    youtube = models.CharField(max_length=300, default='')
    description = models.TextField(blank=True)
    year = models.PositiveIntegerField()
    country = models.CharField(max_length=40)
    age = models.PositiveIntegerField()
    seasons = models.PositiveIntegerField()
    rating = models.DecimalField(max_digits=2, decimal_places=1)
    created = models.DateTimeField(auto_now_add=True)
    uploaded = models.DateTimeField(auto_now=True)
    available = models.BooleanField(default=True)

    class Meta:
        ordering= ('name',)
        index_together = (('id','slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('films:film_detail', args=[self.id, self.slug])

class Comment(models.Model):
    film = models.ForeignKey(Film, related_name='comments')
    name = models.CharField(max_length=50)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Commented by {} on {}'.format(self.name, self.film)

class News(models.Model):
    title = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    body = models.TextField()
    added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-added',)

    def __str__(self):
        words = self.body.split()
        countWords = int(len(words)/2)
        if countWords > 100:
            countWords = 100
        st = ''
        for i in range(countWords):
            st += words[i]
            st +=' '
        return st +'...'

    def get_absolute_url(self):
        return reverse('films:news_info', args=[self.slug])


class Actor(models.Model):
    name = models.CharField(max_length=20, db_index=True)
    film = models.ManyToManyField(Film)
    slug = models.SlugField(max_length=20, db_index=True, unique=True)
    filmSlug = models.CharField(max_length=50)
    photo = models.ImageField(upload_to='actors', blank=True)
    description = models.TextField(blank=True)

    class Meta:
        ordering=('name',)
        verbose_name = 'actor'
        verbose_name_plural = 'actors'

    def __str__(self):
        words = self.description.split()
        countWords = int(len(words)/2)
        if countWords > 100:
            countWords = 100
        st = ''
        for i in range(countWords):
            st += words[i]
            st +=' '
        return st +'...'



    def get_absolute_url(self):
        return reverse('films:actor_info', args=[self.slug])

films/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('email', 'body')

films/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Film, Comment, News, Actor
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CommentForm



def news_info(request, slug):
    one_news = get_object_or_404(News, slug=slug)
    return render(request, 'films/film/one_news.html', {'one_news': one_news})

def film_detail(request, id, slug):
    film = get_object_or_404(Film, id=id, slug=slug)
    comments = film.comments.filter(active=True)
    actors = Actor.objects.filter(filmSlug=slug)
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.film = film
            new_comment.name = request.user.first_name
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request, 'films/film/detail.html',{'film': film,
                                                     'comments': comments,
                                                     'comment_form': comment_form,
                                                     'actors': actors})

def film_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    news = News.objects.all()[:3]
    films = Film.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        films = films.filter(category=category)

    paginator = Paginator(films, 4)
    page = request.GET.get('page')
    try:
        films = paginator.page(page)
    except PageNotAnInteger:
        films = paginator.page(1)
    except EmptyPage:
        films = paginator.page(paginator.num_pages)
    return render(request, 'films/film/list.html', {'page': page,
                                                    'category': category,
                                                    'news': news,
                                                    'categories': categories,
                                                    'films': films})

def show_all_news(request):
    All_news = News.objects.all()
    paginator = Paginator(All_news, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'films/film/news.html', {'page': page,
                                                        'posts': posts})

def actors_list(request):
    actors = Actor.objects.all()
    paginator = Paginator(actors, 4)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'films/film/actors_list.html', {'page': page,
                                                            'posts': posts})

def actor_info(request, slug):
    actor = get_object_or_404(Actor, slug=slug)
    return render(request, 'films/film/actor.html', {'actor': actor})

films/templates/films/film/actor.html
{% extends "films/base.html" %}
{% load static %}

{% block content %}
  <table>
    <tr>
      <td>
        <img style="width:364px; height:536px;" src="{% if actor.photo %}{{ actor.photo.url }}{% else %}
        {% static "img/no_image.png" %}{% endif %}">
      </td>
      <td>
        <h1> {{ actor.name }}</h1>
        <p>Film: {{ actor.film }}</p>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <p> {{ actor.description|linebreaks }}</p>
      </td>
    </tr>
  </table>
{% endblock %}

films/templates/films/film/actors_list.html
{% extends "films/base.html" %}
{% load static %}

{% block content %}
  {% for actor in posts %}
    <div class="acto">
      <table>
        <tr>
          <td>
            <a href="{{ actor.get_absolute_url }}">
              <img style="width:182px; height:268px;" src="{% if actor.photo %}{{ actor.photo.url }}{% else %}
              {% static "img/no_image.png" %}{% endif %}">
            </a>
          </td>
          <td>
            <h3>Info</h3>
            <p>{{ actor|linebreaks }}</p>
          </td>
        </tr>
        <tr>
          <td colspan=2>
            <a href="{{ actor.get_absolute_url }}">
              <center><p style="background-color:#FFFFCC; border: 2px solid #FF0066; font-size:20px"> {{ actor.name }}</p></center>
            </a>
          </td>
        </tr>
      </table>
    </div>
  {% endfor %}
  <center><div class="pag">
    {% include "pagination.html" with page=posts %}
  </div></center>
{% endblock %}

films/templates/films/film/detail.html
{% extends "films/base.html" %}
{% load static %}

{% block title %}
  {% if category %}{{ category.title }}{% else %}Films{% endif %}
{% endblock %}

{% block content %}
  <div id="deta">
    <img style="width:364px; height:536px;" src="{% if film.image %}{{ film.image.url }}{% else %}
      {% static "img/no_image.png" %}{% endif %}">
    <h1>{{ film.name }}</h1>
    <h3>Category: <a href="{{ film.category.get_absolute_url }}">{{ film.category }}</a></h3>
    <h3>V glavnih rolyah: </h3>
    {% for actor in actors %}
      <a href="{{ actor.get_absolute_url }}">
        <h3>{{ actor.name }}</h3>
      </a>
    {% endfor %}
    <h3>Description:</h3>
    <p>{{ film.description|linebreaks }}</p>
    <p><b>Rating:</b> {{ film.rating }}</p>
    <p><b>Year:</b> {{ film.year }}</p>
    <p><b>Country:</b> {{ film.country }}</p>
    <p><b>Age:</b> {{ film.age }}</p>
    <p><b>Seasons:</b> {{ film.seasons }}</p>
    <h3>Trailer:</h3>
    <iframe width="420" height="315" src="{{ film.youtube }}"></iframe>
    <div class="comen">
      {% with comments.count as total_comments %}
        <h2>
          {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
      {% endwith %}
      {% for comment in comments %}
        <p>
          Comment {{ forloop.counter }} by {{ comment.name }}
          {{ comment.created }}
        </p>
        {{ comment.body|linebreaks }}
      {% endfor %}
      {% if new_comment %}
        <h2>Your comment has been added.</h2>
      {% else %}
        <h2>Add a new comment</h2>
        <form action="." method="post">
          {{ comment_form.as_p }}
          {% csrf_token %}
          <p><input type="submit" value="Add comment"></p>
        </form>
      {% endif %}
    </div>
  </div>
{% endblock %}

films/templates/films/film/list.html
{% extends "films/base.html" %}
{% load static %}

{% block title %}
  {% if category %}{{category.name }}{% else %}Films{% endif %}
{% endblock %}

{% block content %}
  <div class="news_place">
    <center><h1>News</h1></center>
    <ul class="news">
      {% for c in news %}
        <div class="oneNews">
          <li class="title">
            {{ c.title }}
          </li>
          <li class="bod">
            {{ c }}
          </li>
          <li>
            <p><a href="{{ c.get_absolute_url }}">See more</a></p>
          </li>
        </div>
      {% endfor %}
    <center><h1> FILMS</h1></center>
    </ul>
  </div>
  <table id='tab'>
    <tr>
      <th colspan=2>
        <h1>{% if category %}{{ category.name }}{% else %}All{% endif %}</h1>
      </th>
      <th rowspan=5 valign="top" style="background-color:#F8F8F8; width:250px;">
        <h1 style="color:#707070;">Categories</h1>
        <ul>
          <li class="categor">
            <a href="{% url "films:film_list" %}">All</a>
          </li>
          {% for cat in categories %}
            <li class="categor">
              <a href="{{ cat.get_absolute_url}}">{{ cat.name }}</a>
            </li>
          {% endfor %}
        </ul>
      </th>
      {% for film in films %}
        <tr>
          <th>
            <a href="{{ film.get_absolute_url }}">
              <img src="{% if film.image %}{{ film.image.url }}{% else %}
              {% static "img/no_image.png" %}{% endif %}">
            </a>
          </th>
          <th>
            <a href="{{ film.get_absolute_url }}">{{ film.name }}</a><br>
            <p>Rating: {{ film.rating }}</p>
            <p>Created in {{ film.year }} year</p>
            <p>was made in {{ film.country }}</p>
            <p>seasons: {{ film.seasons }}</p>
          </th>
        </tr>
      {% endfor %}
    </tr>
  </table>
  <center><div class="pag">
    {% include "pagination.html" with page=films %}
  </div></center>
{% endblock %}

films/templates/films/film/news.html
{% extends "films/base.html" %}
{% load static %}

{% block content %}
  {% for news in posts %}
    <div class="news_page">
      <div class="title">
        <h3> {{ news.title }}</h3>
      </div>
      <div class="news_body">
        <p> {{ news|linebreaks }}</p>
      </div>
      <p><a href="{{ news.get_absolute_url }}">See more</a></p>
      <p>published {{ news.added }}</p>
    </div>
  {% endfor %}
  <center><div class="pag">
    {% include "pagination.html" with page=posts %}
  </div></center>
{% endblock %}

films/templates/films/film/one_news.html
{% extends "films/base.html" %}
{% load static %}

{% block content %}
  <div class="news_page">
    <div class="title">
      <h3> {{ one_news.title }}</h3>
    </div>
    <div class="news_body">
      <p> {{ one_news.body|linebreaks }}</p>
    </div>
    <p>published {{ one_news.added }}</p>
  </div>
{% endblock %}